Test1
prboard-test-org/testrepo pull request #38
Opened 2019-11-03 21:44 UTC by ivanbokiitest

sdfsadfasdfsdf

2019-11-03 23:39 UTC, ivanbokii commented
yeah, not sure about this one

2019-11-03 23:39 UTC, ivanbokii submitted a review, later dismissed

2019-11-07 21:38 UTC, ivanbokii requested changes
I don't think you've covered all the edge cases

2019-11-07 22:37 UTC, ivanbokii approved these changes

2019-11-07 22:47 UTC, ivanbokii requested changes
I want some changes

2019-11-07 22:47 UTC, ivanbokii submitted a review, later dismissed

2019-11-07 23:16 UTC, ivanbokii submitted a review, later dismissed
well, what the fff

2019-11-07 23:19 UTC, ivanbokii submitted a review, later dismissed

2019-11-07 23:21 UTC, ivanbokii requested changes
requesting stupid changes

2019-11-07 23:22 UTC, ivanbokii submitted a review, later dismissed

2019-11-07 23:27 UTC, ivanbokii submitted a review, later dismissed
well, actually I changed my mind

2019-11-07 23:29 UTC, ivanbokii approved these changes
aproving this

2019-11-07 23:29 UTC, ivanbokii submitted a review, later dismissed
changing my decision

2019-11-07 23:30 UTC, ivanbokii approved these changes

2019-11-07 23:31 UTC, ivanbokii submitted a review, later dismissed
nah nah nah

2019-11-07 23:31 UTC, ivanbokii reviewed
nah, just want to do a random comment

2019-11-07 23:33 UTC, ivanbokii requested changes
123123123123

2019-11-07 23:33 UTC, ivanbokii commented on .eslintrc
> +{
sssss

2019-11-07 23:33 UTC, ivanbokii reviewed
meh meh

2019-11-07 23:34 UTC, ivanbokii approved these changes

2019-12-02 21:43 UTC, ivanbokii approved these changes

2019-12-02 21:45 UTC, ivanbokii approved these changes

2019-12-02 21:45 UTC, ivanbokii approved these changes

2019-12-02 21:51 UTC, ivanbokii approved these changes

2019-12-02 21:52 UTC, ivanbokii submitted a review, later dismissed

2020-03-22 17:36 UTC, ivanbokiitest commented
omg, just go away

2020-03-22 17:40 UTC, ivanbokii requested changes
I don't really like it

2020-03-22 17:43 UTC, closed without merging